matrix:
  include:
    - language: java
      jdk:
        - openjdk8
        - oraclejdk8

    - language: android
      jdk:
        - openjdk8
        - oraclejdk8
      android:
        components:
          - tools
          - platform-tools

cache:
  directories:
    - $HOME/.m2

install: mvn install --quiet -DskipTests=true -Dgpg.skip=true

after_success:
  - mvn clean test jacoco:report coveralls:report -P coverage
