matrix:
  include:
    - language: java
      jdk: openjdk8

    - language: java
      jdk: oraclejdk8

    - language: android
      jdk: openjdk8

    - language: android
      jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

install: mvn install --quiet -DskipTests=true -Dgpg.skip=true

after_success:
  - mvn clean test jacoco:report coveralls:report -P coverage
