matrix:
  include:
    - language: java

    - language: android
      android:
        components:
          - tools
          - platform-tools

jdk:
  - openjdk8
  - oraclejdk8

install: mvn install --quiet -DskipTests=true -Dgpg.skip=true

after_success:
  - mvn clean test jacoco:report coveralls:report -P coverage
